# Generated by Django 5.1.1 on 2025-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datefolder',
            name='full_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
