# Generated by Django 5.1.1 on 2025-08-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_datefolder_full_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.category'),
        ),
    ]
