# Generated by Django 5.1.1 on 2025-08-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_medicalfile_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-login_time']},
        ),
    ]
